### ISSUE TITLE
Support # as comment char in csv file

### ISSUE THREAD

**Issue by DonLakeFlyer** [dynamic-and-active-systems-lab/uavrt_bearing#2]
I'm going to change Tag Tracker to output headings comments to show what the record order is

**Comment by DonLakeFlyer** [comment]
Latest version of Tag Tracker does this

**Comment by mwshafer** [comment]
I am adding this support. Can you send the headers or send me an example rotation csv file with the headers so that I can use them to test the updates?

**Comment by DonLakeFlyer** [comment]
I don't have one with comments right now. Just add lines which start with # anywhere and make sure your code just ignores them.

**Comment by mwshafer** [comment]
Done with commit: 7a367083de87cdad32f1b29a2aee17a080317889
