### ISSUE TITLE
Question: Should pulses in rotation csv only be from vehicle stopped at rotation point

### ISSUE THREAD

**Issue by DonLakeFlyer** [dynamic-and-active-systems-lab/uavrt_bearing#4]
For my compass rose bearing calc/display I only use pulses from when the vehicle is standing still paused at a specific rotation angle. Currently the rotation csv file contains all pulses from rotation start to stop. Including the ones when the vehicle is moving. Given the fact that the pulses detected while the vehicle is moving are at possible lower quality do you want me to change to only include the standing still pulses?

**Comment by mwshafer** [comment]
I think this might be a good idea. Only because I am seeing a difference in SNR when the vehicle is in motion vs. flying due to the additional RFI.

**Comment by DonLakeFlyer** [comment]
Ok, I'll change it
